### ISSUE TITLE
Report name

### ISSUE THREAD

**Issue by tikohatico** [Vanare/behat-cucumber-formatter#5]
Hi there
Is there an option to specify file name of a report via CLI arguments?
We run test in parallel and certain report name form behat.yml will be overridden by each process.

for ex. 
`bin/behat --format="json" --out="build/specific_name.json`

Thanks.

**Comment by mytord** [comment]
Hi,

Now, we're using a fixed filename and Behat overwrite this file after each build. You should specify it by using `filename` and `outputDir` options in behat.yml

**Comment by tikohatico** [comment]
Hi, is there a luck to get extended it to work with CLI?

**Comment by mytord** [comment]
Hi, 

You can try to use this:

```
bin/behat --format=cucumber_json --out=build/subdir1
bin/behat --format=cucumber_json --out=build/subdir2
```

These commands will create two separate files

```
build/subdir1/report.json
build/subdir2/report.json
```

**Comment by tikohatico** [comment]
Hi, thanks, I see, I will use this approach)
