### ISSUE TITLE
Scenario Outline supporting

### ISSUE THREAD

**Issue by tikohatico** [Vanare/behat-cucumber-formatter#6]
Hi there
It seems will be the best behat reporter when scenario outline will be supported, isn't?

**Comment by smirik** [comment]
Hey!
Sorry, didn't get you.

**Comment by tikohatico** [comment]
have a look please

```
Scenario: JSON formatter is generated with scenario outline
     Given I run Behat with "json"
     Then I should see report file is "report.json"

```

when I run 

`tiko@tiko /v/w/d/behat-bdd> bin/behat features/outline/Scenario.feature   --dry-run -f cucumber_json
`
**then the reports is generated**

`[{
    "uri": "\/var\/www\/designow\/behat-idevels\/features\/outline\/Scenario.feature",
    "id": "outline",
    "tags": [],
    "keyword": "Feature",
    "name": "Outline",
    "line": 0,
    "description": "In order to get reported from scenarios outline\nbehat-cucumber-formatter should be able to work with them",
    "elements": [{
        "id": "json-formatter-is-generated-with-scenario-outline;outline",
        "tags": [],
        "keyword": "Scenario",
        "name": "JSON formatter is generated with scenario outline",
        "line": 5,
        "description": "",
        "type": "scenario",
        "steps": [{
            "keyword": "Given",
            "name": "I run Behat with \"json\"",
            "line": 6,
            "match": {
                "location": ""
            },
            "result": {
                "status": "skipped",
                "error_message": null,
                "duration": 222000000
            }
        }, {
            "keyword": "Then",
            "name": "I should see report file is \"report.json\"",
            "line": 7,
            "match": {
                "location": ""
            },
            "result": {
                "status": "skipped",
                "error_message": null,
                "duration": 231000000
            }
        }],
        "examples": []
    }]
}]`

**When scenarios is outline, we have errors.**

```

 Scenario Outline: JSON formatter is generated with scenario outline
    Given I run Behat with "<formatter>"
    Then I should see report file is "<file>"
    Examples:
      | formatter | file        |
      | xml       | report.xml  |
      | json      | report.json |

```

`tiko@tiko /v/w/d/behat-bdd> bin/behat features/outline/Outline.feature  --dry-run -f cucumber_json
PHP Fatal error:  Call to a member function getId() on null in /var/www/designow/behat-bdd/vendor/vanare/behat-cucumber-json-formatter/src/Node/Scenario.php on line 156
PHP Stack trace:
PHP   1. {main}() /var/www/designow/behat-bdd/vendor/behat/behat/bin/behat:0
PHP   2. Symfony\Component\Console\Application->run() /var/www/designow/behat-bdd/vendor/behat/behat/bin/behat:31
PHP   3. Behat\Testwork\Cli\Application->doRun() /var/www/designow/behat-bdd/vendor/symfony/console/Application.php:117
PHP   4. Symfony\Component\Console\Application->doRun() /var/www/designow/behat-bdd/vendor/behat/behat/src/Behat/Testwork/Cli/Application.php:121
PHP   5. Symfony\Component\Console\Application->doRunCommand() /var/www/designow/behat-bdd/vendor/symfony/console/Application.php:186
PHP   6. Symfony\Component\Console\Command\Command->run() /var/www/designow/behat-bdd/vendor/symfony/console/Application.php:787
PHP   7. Behat\Testwork\Cli\Command->execute() /var/www/designow/behat-bdd/vendor/symfony/console/Command/Command.php:256
PHP   8. Behat\Testwork\Tester\Cli\ExerciseController->execute() /var/www/designow/behat-bdd/vendor/behat/behat/src/Behat/Testwork/Cli/Command.php:63
PHP   9. Behat\Testwork\Tester\Cli\ExerciseController->testSpecifications() /var/www/designow/behat-bdd/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php:108
PHP  10. Behat\Testwork\Ordering\OrderedExercise->tearDown() /var/www/designow/behat-bdd/vendor/behat/behat/src/Behat/Testwork/Tester/Cli/ExerciseController.php:147
PHP  11. Behat\Testwork\EventDispatcher\Tester\EventDispatchingExercise->tearDown() /var/www/designow/behat-bdd/vendor/behat/behat/src/Behat/Testwork/Ordering/OrderedExercise.php:94
PHP  12. Behat\Testwork\EventDispatcher\TestworkEventDispatcher->dispatch() /var/www/designow/behat-bdd/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/Tester/EventDispatchingExercise.php:84
PHP  13. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() /var/www/designow/behat-bdd/vendor/behat/behat/src/Behat/Testwork/EventDispatcher/TestworkEventDispatcher.php:39
PHP  14. call_user_func:{/var/www/designow/behat-bdd/vendor/symfony/event-dispatcher/EventDispatcher.php:171}() /var/www/designow/behat-bdd/vendor/symfony/event-dispatcher/EventDispatcher.php:171
PHP  15. Vanare\BehatCucumberJsonFormatter\Formatter\Formatter->onAfterExercise() /var/www/designow/behat-bdd/vendor/symfony/event-dispatcher/EventDispatcher.php:171
PHP  16. Vanare\BehatCucumberJsonFormatter\Renderer\JsonRenderer->render() /var/www/designow/behat-bdd/vendor/vanare/behat-cucumber-json-formatter/src/Formatter/Formatter.php:330
PHP  17. Vanare\BehatCucumberJsonFormatter\Renderer\JsonRenderer->processSuite() /var/www/designow/behat-bdd/vendor/vanare/behat-cucumber-json-formatter/src/Renderer/JsonRenderer.php:37
PHP  18. Vanare\BehatCucumberJsonFormatter\Renderer\JsonRenderer->processFeature() /var/www/designow/behat-bdd/vendor/vanare/behat-cucumber-json-formatter/src/Renderer/JsonRenderer.php:67
PHP  19. Vanare\BehatCucumberJsonFormatter\Renderer\JsonRenderer->processScenario() /var/www/designow/behat-bdd/vendor/vanare/behat-cucumber-json-formatter/src/Renderer/JsonRenderer.php:94
PHP  20. Vanare\BehatCucumberJsonFormatter\Node\Scenario->getId() /var/www/designow/behat-bdd/vendor/vanare/behat-cucumber-json-formatter/src/Renderer/JsonRenderer.php:109
`

**Comment by mytord** [comment]
Hi,

Thanks, we will try to fix this as soon as possible.

**Comment by mytord** [comment]
https://github.com/Vanare/behat-cucumber-formatter/commit/5576259538301319d697dd3e052bc7fdb99b6dca

**Comment by alextarasov** [comment]
I face the same issue. Other features I tested that use "scenario" works ok.
btw - thank you for this extension - works and looks nice with Jenkins
