### ISSUE TITLE
 Step duration calculation

### ISSUE THREAD

**Issue by tikolakin** [Vanare/behat-cucumber-formatter#7]
Hi there

I just wondering whether time calculation is correct 
Please see attachment and corespondent json
I'm using this plugin to parse report 
https://github.com/jenkinsci/cucumber-reports-plugin
![2928x954-selection_17_03_2016_021](https://cloud.githubusercontent.com/assets/5860505/13848536/01525d0c-ec5b-11e5-9fce-2f53b618a63c.png)

```
 "keyword":"Scenario",
            "name":"Creating an open challenge",
            "line":7,
            "description":"",
            "type":"scenario",
            "steps":[
               {
                  "keyword":"Given",
                  "name":"I am logged in as staff user",
                  "line":8,
                  "match":{
                     "location":""
                  },
                  "result":{
                     "status":"passed",
                     "error_message":null,
                     "duration":24336000000
                  }
               },
               {
                  "keyword":"Given",
                  "name":"I am on open challenge creating page",
                  "line":9,
                  "match":{
                     "location":""
                  },
                  "result":{
                     "status":"passed",
                     "error_message":null,
                     "duration":25072000000
                  }
               }
```

**Comment by pluseg** [comment]
Hi @tikolakin! We know this bug but haven't time for fixing it. We should use time diff between steps instead of absolute offset. If you fix it it will be great, PRs are welcome!

**Comment by tikolakin** [comment]
Hi
it should
but I've noticed that https://github.com/Vanare/behat-cucumber-formatter/blob/master/src/Formatter/Formatter.php#L448
is never executed. It might be an issue on behat side.

**Comment by guillaumeray** [comment]
Indeed, behat hook BehatEvent\BeforeStepTested seems to doesnt work.
But i have a dirty way to fix the issue. You can simulate onBeforeStepTested function at the end of onAfterStepTested function.

If you have a better way to solve the issue feel free to add your solution

   ```php
    /**
     * @param BehatEvent\AfterStepTested $event
     */
    public function onAfterStepTested(BehatEvent\StepTested $event)
    {
        $this->timer->stop();

        $result = $event->getTestResult();

        $step = new Node\Step();
        $step->setKeyword($event->getStep()->getKeyword());
        $step->setName($event->getStep()->getText());
        $step->setLine($event->getStep()->getLine());
        $step->setArguments($event->getStep()->getArguments());
        $step->setResult($result);
        $step->setResultCode($result->getResultCode());
        $step->setDuration($this->timer->getSeconds());

        $this->processStep($step, $result);

        $this->currentScenario->addStep($step);

        // simulate onBeforeStepTested in starting timer for the next step
        $this->timer->start();
    }
```

**Comment by robert-tom** [comment]
'tester.step_tested.before' => 'onBeforeStepTested' is missing in the register events 

https://github.com/Vanare/behat-cucumber-formatter/blob/b28ae403404be4c74c740a3948d9338fc51443a3/src/Formatter/Formatter.php#L136

Add this and it will work.

**Comment by bitcoder** [comment]
Hi,
I've found out that the step information seems to be missing whenever using Scenario Outlines.
I'm using the code from the PR #20 that adds support for scenario outlines.

this is what we see in our test management solution (i.e. Xray).
![image](https://user-images.githubusercontent.com/553801/54040745-0087c400-41be-11e9-819b-59b27dc03cb5.png)

This is the json report  containing the information for the scenario outline
[report.txt](https://github.com/Vanare/behat-cucumber-formatter/files/2946596/report.txt)
